name: "Enhancement"
description: "Propose a new enhancement or improvement."
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement
        Please provide as much detail as possible.
  - type: input
    id: title
    attributes:
      label: "Enhancement Title"
      placeholder: "Short summary of the enhancement"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What is the enhancement?"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this enhancement needed?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "How should it work?"
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any alternative solutions or features considered."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Screenshots, references, or other context."
    validations:
      required: false