name: "Feature Request"
description: "Propose a new feature or enhancement."
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please provide as much detail as possible.
  - type: input
    id: title
    attributes:
      label: "Feature Title"
      placeholder: "Short summary of the feature"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What is the feature?"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature needed?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "How should it work?"
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any alternative solutions or features considered."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Screenshots, references, or other context."
    validations:
      required: false
